import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Search,RefreshCw,History,Trash2,ExternalLink,Database,UserRound,BookOpen,Activity,ChevronRight,Clock3,CheckCircle2,AlertCircle,Building2,Hash,BarChart3,Link2} from 'lucide-react';
import './styles.css';
import './metric-overrides.css';
import './card-redesign.css';
import { ExtrasNavButtons, ExtrasMobileNavButtons, ExtrasPage } from './extras.jsx';
const EXTRA_PAGES = new Set(['exports', 'review', 'analytics', 'operations']);
const API=import.meta.env.VITE_API_URL??(import.meta.env.DEV?'http://127.0.0.1:8000':'');

function LoginPage({onLogin}){const [username,setUsername]=useState('');const [password,setPassword]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const submit=async event=>{event.preventDefault();setBusy(true);setError('');try{const response=await fetch(API+'/api/v1/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password})});const result=await response.json();if(!response.ok)throw new Error(result.detail||'Unable to sign in.');localStorage.setItem('researchpulse_session',result.access_token);onLogin(result.username)}catch(loginError){setError(loginError.message)}finally{setBusy(false)}};return <main className="login-page"><section className="login-visual"><div className="login-brand"><div className="mark"><Activity/></div><div><strong>ResearchPulse</strong><span>Faculty Research Intelligence</span></div></div><div className="login-intro"><span className="eyebrow">PRIVATE RESEARCH WORKSPACE</span><h1>Bring every faculty profile into focus.</h1><p>Securely access verified directories, source-separated metrics, live synchronization, and historical research evidence.</p></div><div className="login-proof"><span><CheckCircle2 size={15}/> Verified VFSTR sources</span><span><Database size={15}/> Multi-source metrics</span><span><RefreshCw size={15}/> Live synchronization</span></div></section><section className="login-panel"><div className="login-card"><span className="label">WELCOME BACK</span><h2>Sign in to ResearchPulse</h2><p className="login-subtitle">Use your workspace credentials to continue.</p><form onSubmit={submit}><label>Username<input value={username} onChange={event=>setUsername(event.target.value)} autoComplete="username" placeholder="Enter username" required /></label><label>Password<input value={password} onChange={event=>setPassword(event.target.value)} autoComplete="current-password" type="password" placeholder="Enter password" required /></label>{error&&<div className="notice error"><AlertCircle size={16}/>{error}</div>}<button className="primary login-submit" disabled={busy}>{busy?'Signing in...':'Sign in'}<ChevronRight size={17}/></button></form><small className="login-footnote">Your session expires automatically after the configured session period.</small></div></section></main>}

function App(){
 const [session,setSession]=useState(()=>localStorage.getItem('researchpulse_session')), [page,setPage]=useState(window.location.pathname==='/authors'?'authors':'search'),[lastName,setLastName]=useState(''),[firstName,setFirstName]=useState(''),[institution,setInstitution]=useState(''),[publications,setPublications]=useState([]),[profile,setProfile]=useState(null),[history,setHistory]=useState([]),[loading,setLoading]=useState(false),[syncing,setSyncing]=useState(false),[error,setError]=useState(''),[health,setHealth]=useState(null),[lastSync,setLastSync]=useState(null),[authorCount,setAuthorCount]=useState(0),[authors,setAuthors]=useState([]),[departments,setDepartments]=useState([]),[schools,setSchools]=useState([]),[designations,setDesignations]=useState([]),[researchAreas,setResearchAreas]=useState([]),[authorSearch,setAuthorSearch]=useState(''),[authorDepartment,setAuthorDepartment]=useState(''),[authorSchool,setAuthorSchool]=useState(''),[authorDesignation,setAuthorDesignation]=useState(''),[authorResearchArea,setAuthorResearchArea]=useState(''),[authorHasScholar,setAuthorHasScholar]=useState(''),[authorHasScopus,setAuthorHasScopus]=useState(''),[authorDataStatus,setAuthorDataStatus]=useState(''),[authorSort,setAuthorSort]=useState('name_az'),[authorPage,setAuthorPage]=useState(1),[authorPageSize]=useState(24),[authorTotal,setAuthorTotal]=useState(0),[authorsLoading,setAuthorsLoading]=useState(false),[authorsError,setAuthorsError]=useState(''),[authorRefreshBusy,setAuthorRefreshBusy]=useState(false),[authorRefreshReport,setAuthorRefreshReport]=useState(null),[metricImportBusy,setMetricImportBusy]=useState(false),[metricImportReport,setMetricImportReport]=useState(null),[directoryRevision,setDirectoryRevision]=useState(0);
 const logout=()=>{localStorage.removeItem('researchpulse_session');setSession(null);setProfile(null)};
 const fetch=(url,options={})=>{const headers=new Headers(options.headers||{});const token=localStorage.getItem('researchpulse_session');if(token)headers.set('Authorization',`Bearer ${token}`);return window.fetch(url,{...options,headers})};
 useEffect(()=>{if(session){loadHealth();loadHistory();loadAuthorCount();setDirectoryRevision(value=>value+1)}},[session]);
 const loadHealth=async()=>{try{const r=await apiFetch('/api/v1/health');setHealth(await r.json())}catch{setHealth(null)}};
 const loadHistory=async()=>{try{const r=await apiFetch('/api/v1/history');if(r.ok)setHistory(await r.json())}catch{}}
 const loadAuthorCount=async()=>{try{const r=await apiFetch('/api/v1/authors?page=1&page_size=1');if(r.ok)setAuthorCount((await r.json()).total)}catch{setAuthorCount(0)}};
 const navigate=next=>{if(next==='authors')window.history.pushState({},'','/authors');else if(EXTRA_PAGES.has(next))window.history.pushState({},'','/'+next);else if(window.location.pathname!=='/')window.history.pushState({},'','/');setPage(next)};
 useEffect(()=>{loadHealth();loadHistory();loadAuthorCount();const route=()=>{const path=window.location.pathname.replace(/^\//,'');return path==='authors'?'authors':EXTRA_PAGES.has(path)?path:'search'};const onPopState=()=>setPage(route());setPage(route());window.addEventListener('popstate',onPopState);return()=>window.removeEventListener('popstate',onPopState)},[]);
 useEffect(()=>{if(page!=='profile'||!profile)return;const id=setInterval(async()=>{try{const r=await fetch(API+'/api/v1/faculty/'+profile.id);if(r.ok)setProfile(await r.json())}catch{}},60000);return()=>clearInterval(id)},[page,profile?.id]);
 useEffect(()=>{if(page!=='authors')return;let cancelled=false;const load=async()=>{setAuthorsLoading(true);setAuthorsError('');try{const params=new URLSearchParams({search:authorSearch,department:authorDepartment,school:authorSchool,designation:authorDesignation,research_area:authorResearchArea,sort:authorSort,page:String(authorPage),page_size:String(authorPageSize)});if(authorHasScholar)params.set('has_google_scholar',authorHasScholar);if(authorHasScopus)params.set('has_scopus',authorHasScopus);if(authorDataStatus)params.set('data_status',authorDataStatus);const [listResponse,departmentResponse]=await Promise.all([fetch(API+'/api/v1/authors?'+params),fetch(API+'/api/v1/authors/departments')]);if(!listResponse.ok)throw new Error((await listResponse.json()).detail||'Could not load the VFSTR directory.');const list=await listResponse.json();if(cancelled)return;setAuthors(list.authors);setAuthorTotal(list.total);setAuthorCount(list.total);if(departmentResponse.ok){const facets=await departmentResponse.json();setDepartments(facets.departments||[]);setSchools(facets.schools||[]);setDesignations(facets.designations||[]);setResearchAreas(facets.research_areas||[])}}catch(e){if(!cancelled)setAuthorsError(e.message)}finally{if(!cancelled)setAuthorsLoading(false)}};load();return()=>{cancelled=true}},[page,authorSearch,authorDepartment,authorSchool,authorDesignation,authorResearchArea,authorHasScholar,authorHasScopus,authorDataStatus,authorSort,authorPage,authorPageSize,directoryRevision]);
 useEffect(()=>{if(page!=='authors')return;let cancelled=false;fetch(API+'/api/v1/authors/metrics/import-report').then(response=>response.ok?response.json():null).then(result=>{if(!cancelled&&result?.report)setMetricImportReport(result.report)}).catch(()=>{});return()=>{cancelled=true}},[page,directoryRevision]);
 const refreshAuthors=async()=>{setAuthorRefreshBusy(true);setAuthorRefreshReport(null);try{const response=await fetch(API+'/api/v1/authors/refresh',{method:'POST'});const result=await response.json();if(!response.ok)throw new Error(result.detail||'Official VFSTR directory refresh failed.');setAuthorRefreshReport(result);setAuthorCount(result.author_count);setDirectoryRevision(value=>value+1)}catch(refreshError){setAuthorRefreshReport({status:'error',error_message:refreshError.message,updated:0,failed_records:[]})}finally{setAuthorRefreshBusy(false)}};
 const importMetrics=async()=>{setMetricImportBusy(true);setMetricImportReport(null);try{const response=await fetch(API+'/api/v1/authors/metrics/import',{method:'POST'});const result=await response.json();if(!response.ok)throw new Error(result.detail||'Metrics import failed.');setMetricImportReport(result);setDirectoryRevision(value=>value+1)}catch(importError){setMetricImportReport({import_failures:[],imported_count:0,import_error:importError.message})}finally{setMetricImportBusy(false)}};
 const search=async e=>{e?.preventDefault();if(!lastName.trim())return;const name=firstName.trim()?`${lastName.trim()}, ${firstName.trim()}`:lastName.trim();setLoading(true);setError('');setPublications([]);try{const r=await fetch(API+'/api/v1/faculty/search',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,institution,department:''})});const data=await r.json();if(!r.ok)throw new Error(data.detail||'Scopus publication search failed.');setPublications(data);if(!data.length)setError('No matching Scopus publications were returned. Check the spelling or broaden/remove the affiliation.')}catch(e){setError(e.message)}finally{setLoading(false)}};
 const openHistory=async id=>{setLoading(true);try{const r=await fetch(API+'/api/v1/faculty/'+id);if(!r.ok)throw new Error('Profile not found');setProfile(await r.json());setPage('profile')}catch(e){setError(e.message)}finally{setLoading(false)}};
 const sync=async()=>{if(!profile)return;setSyncing(true);setError('');try{const r=await fetch(API+'/api/v1/faculty/'+profile.id+'/sync',{method:'POST'});const data=await r.json();if(!r.ok)throw new Error(data.detail||'Synchronization failed');const p=await fetch(API+'/api/v1/faculty/'+profile.id);setProfile(await p.json());setLastSync(data);await loadHistory();}catch(e){setError(e.message)}finally{setSyncing(false)}};
 const updateConnections=async payload=>{if(!profile)return;setError('');try{const r=await fetch(API+'/api/v1/faculty/'+profile.id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await r.json();if(!r.ok)throw new Error(data.detail||'Could not update profile.');setProfile(data)}catch(e){setError(e.message)}};
 const updateFacultyDetails=async payload=>{if(!profile)return;setError('');try{const r=await fetch(API+'/api/v1/faculty/'+profile.id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await r.json();if(!r.ok)throw new Error(data.detail||'Could not update profile.');setProfile(data)}catch(e){setError(e.message)}};
 const clear=async()=>{if(!confirm('Clear all previous searches?'))return;await fetch(API+'/api/v1/history',{method:'DELETE'});setHistory([])};
 const remove=async id=>{await fetch(API+'/api/v1/history/'+id,{method:'DELETE'});loadHistory()};
 const metrics=useMemo(()=>Object.fromEntries((profile?.metrics||[]).map(m=>[m.source,m])),[profile]);
 if(!session)return <LoginPage onLogin={setSession}/>;
 return <div className="app">
  <header className="top"><div className="brand"><div className="mark"><Activity/></div><div><h1>ResearchPulse</h1><p>Faculty Research Intelligence</p></div></div><div className="top-right"><div className={'live '+(health?'ok':'')}><span/> {health?'System online':'Backend offline'}</div><button className="ghost" onClick={()=>{loadHealth();loadHistory();loadAuthorCount()}}><RefreshCw size={16}/></button><button className="logout-button" onClick={logout}><UserRound size={14}/> Sign out</button></div></header>
  <nav className="mobile-nav" aria-label="Workspace"><button className={page==='search'?'active':''} onClick={()=>navigate('search')}><Search size={16}/>Search</button><button className={page==='profile'?'active':''} disabled={!profile} onClick={()=>navigate('profile')}><UserRound size={16}/>Profile</button><button className={page==='history'?'active':''} onClick={()=>navigate('history')}><History size={16}/>History</button><button className={page==='authors'?'active':''} onClick={()=>navigate('authors')}><BookOpen size={16}/>VFSTR</button><ExtrasMobileNavButtons page={page} navigate={navigate}/></nav>
    <div className="shell">
     <aside><div className="nav-title">WORKSPACE</div><button className={page==='search'?'active':''} onClick={()=>navigate('search')}><Search size={18}/>Faculty Search</button><button className={page==='profile'?'active':''} disabled={!profile} onClick={()=>navigate('profile')}><UserRound size={18}/>Faculty Profile</button><button className={page==='history'?'active':''} onClick={()=>navigate('history')}><History size={18}/>Search History <b>{history.length}</b></button><button className={page==='authors'?'active':''} onClick={()=>navigate('authors')}><BookOpen size={18}/>VFSTR Authors <b>{authorCount}</b></button><div className="nav-title" style={{marginTop:18}}>EXTENDED</div><ExtrasNavButtons page={page} navigate={navigate}/><div className="side-card"><Database size={18}/><strong>Data sources</strong><span>Scopus: {health?.scopus_configured?'Connected':'Needs API key'}</span><span>Scholar: {health?.google_scholar_configured?'Connected':'Optional provider'}</span></div></aside>
   <main>
    {page==='search'&&<><section className="hero"><div><span className="eyebrow">MULTI-SOURCE SCHOLARLY ANALYTICS</span><h2>Find a faculty member.<br/><em>See their research footprint.</em></h2><p>Search Scopus author profiles, compare scholarly metrics, review publications, and keep a historical record of searches and synchronization changes.</p></div><div className="hero-stat"><Activity size={20}/><strong>6h</strong><span>default sync cadence</span></div></section>
    <section className="community"><div><span className="label">VFSTR RESEARCH COMMUNITY</span><h3>VFSTR Authors</h3><p>Verified faculty research directory</p></div><strong>{authorCount}<small> verified authors</small></strong><button className="secondary" onClick={()=>navigate('authors')}>Browse authors <ChevronRight size={15}/></button></section>
    <section className="search-card"><div className="section-head"><div><span className="label">01 · FACULTY LOOKUP</span><h3>Search research profile</h3></div><span className="provider"><span/>Live source search</span></div><form onSubmit={search} className="form"><div className="field"><label>Last name <small>required</small></label><input value={lastName} onChange={e=>setLastName(e.target.value)} placeholder="Enter last name" required/></div><div className="field"><label>First name <small>optional</small></label><input value={firstName} onChange={e=>setFirstName(e.target.value)} placeholder="Enter first name"/></div><div className="field"><label>Affiliation <small>optional</small></label><input value={institution} onChange={e=>setInstitution(e.target.value)} placeholder="University or institution"/></div><button className="primary" disabled={loading||!lastName.trim()}><Search size={18}/>{loading?'Searching...':'Search faculty'}</button></form>{error&&<div className="notice error"><AlertCircle size={16}/>{error}</div>}</section>
    <div className="metric-note">Scopus Search shows publication records only. A record's creator is not a verified faculty identity. Official Scopus Author Profile lookup requires the appropriate Elsevier API entitlement.</div>
    {publications.length>0&&<section className="results"><div className="section-head"><div><span className="label">02 · SCOPUS SEARCH</span><h3>Publication records ({publications.length})</h3></div><span className="muted">Publication metadata from Scopus Search; not an author profile</span></div>{publications.map(p=><article className="candidate" key={p.id}><div className="candidate-main"><strong>{p.title||'Untitled Scopus record'}</strong><span>{p.record_creator?'Record creator: '+p.record_creator:'Creator not included in this record'}{p.affiliation?' · '+p.affiliation:''}</span><small>{p.journal||'Publication'} · {p.year||'Year n/a'} · Scopus Search-derived</small></div><div className="mini-metrics"><span><b>{p.citations??'—'}</b> citations</span></div>{p.url&&<a href={p.url} target="_blank" rel="noreferrer"><ExternalLink size={15}/></a>}</article>)}</section>}
     <section className="info-grid"><Info icon={<Hash/>} title="Citation metrics" text="Track citations, h-index and i10-index separately by source."/><Info icon={<RefreshCw/>} title="Change monitoring" text="Store metric snapshots so increases and decreases are visible after each sync."/><Info icon={<History/>} title="Search history" text="Reopen previous faculty profiles or clear individual/all searches."/></section>
    </>}
    {page==='authors'&&<AuthorsDirectory authors={authors} total={authorTotal} departments={departments} schools={schools} designations={designations} researchAreas={researchAreas} search={authorSearch} setSearch={value=>{setAuthorSearch(value);setAuthorPage(1)}} department={authorDepartment} setDepartment={value=>{setAuthorDepartment(value);setAuthorPage(1)}} school={authorSchool} setSchool={value=>{setAuthorSchool(value);setAuthorPage(1)}} designation={authorDesignation} setDesignation={value=>{setAuthorDesignation(value);setAuthorPage(1)}} researchArea={authorResearchArea} setResearchArea={value=>{setAuthorResearchArea(value);setAuthorPage(1)}} hasScholar={authorHasScholar} setHasScholar={value=>{setAuthorHasScholar(value);setAuthorPage(1)}} hasScopus={authorHasScopus} setHasScopus={value=>{setAuthorHasScopus(value);setAuthorPage(1)}} dataStatus={authorDataStatus} setDataStatus={value=>{setAuthorDataStatus(value);setAuthorPage(1)}} sort={authorSort} setSort={value=>{setAuthorSort(value);setAuthorPage(1)}} page={authorPage} setPage={setAuthorPage} pageSize={authorPageSize} loading={authorsLoading} error={authorsError} refresh={refreshAuthors} refreshBusy={authorRefreshBusy} refreshReport={authorRefreshReport} importMetrics={importMetrics} metricImportBusy={metricImportBusy} metricImportReport={metricImportReport} openProfile={async author=>{try{const r=await fetch(API+'/api/v1/authors/'+author.id+'/profile');if(!r.ok)throw new Error('The verified author profile could not be opened.');setProfile(await r.json());navigate('profile')}catch(e){setAuthorsError(e.message)}}}/>}
    {page==='profile'&&profile&&<Profile profile={profile} metrics={metrics} sync={sync} syncing={syncing} lastSync={lastSync} updateConnections={updateConnections} updateFacultyDetails={updateFacultyDetails}/>} 
    {page==='history'&&<HistoryPage items={history} open={openHistory} remove={remove} clear={clear}/>} 
    {EXTRA_PAGES.has(page)&&<ExtrasPage page={page} navigate={navigate} apiFetch={apiFetch} openProfile={openHistory}/>}
   </main>
  </div><footer>ResearchPulse · Faculty Research Intelligence · Scopus API integration with source attribution · Google Scholar via linked profile/provider</footer>
 </div>
}
function AuthorsDirectory({authors,total,departments,schools,designations,researchAreas,search,setSearch,department,setDepartment,school,setSchool,designation,setDesignation,researchArea,setResearchArea,hasScholar,setHasScholar,hasScopus,setHasScopus,dataStatus,setDataStatus,sort,setSort,page,setPage,pageSize,loading,error,openProfile,refresh,refreshBusy,refreshReport,importMetrics,metricImportBusy,metricImportReport}){
 const pageCount=Math.max(1,Math.ceil(total/pageSize));
 const display=value=>value===null||value===undefined||value===''?'N/A':value;
 return <section className="authors-page">
  <div className="authors-heading"><div><span className="eyebrow">VIGNAN'S FOUNDATION FOR SCIENCE, TECHNOLOGY AND RESEARCH</span><h2>VFSTR Authors</h2><p>Faculty Research Directory</p></div><div className="authors-page-actions"><div className="authors-total"><strong>{total}</strong><span>verified authors</span></div><button className="secondary" disabled={refreshBusy} onClick={refresh}><RefreshCw size={15}/>{refreshBusy?'Refreshing...':'Refresh VFSTR Authors'}</button><button className="secondary" disabled={metricImportBusy} onClick={importMetrics}><Database size={15}/>{metricImportBusy?'Importing...':'Import April 2026 metrics'}</button></div></div>
  {refreshReport&&<div className={'directory-refresh '+(refreshReport.status==='error'?'error':'')}><strong>{refreshReport.status==='error'?'Refresh failed':refreshReport.status==='partial'?'Refresh partially completed':'Refresh complete'}</strong><span>{refreshReport.updated||0} updated · {refreshReport.author_count??total} authors total · {refreshReport.failed_records?.length||0} failed · {refreshReport.unparsed_cards??0} unparsed</span>{refreshReport.error_message&&<span>{refreshReport.error_message}</span>}{refreshReport.failed_records?.map((row,index)=><span key={index}>{row.name}: {row.error}</span>)}</div>}
  {metricImportReport&&<div className={'directory-refresh '+(metricImportReport.import_error||metricImportReport.failed_import_count?'error':'')}><strong>{metricImportReport.import_error?'April metrics import failed':'April 2026 metrics import report'}</strong>{metricImportReport.import_error?<span>{metricImportReport.import_error}</span>:<><span>{metricImportReport.imported_count} imported · {metricImportReport.matched_count} safe matches · {metricImportReport.unmatched_spreadsheet_count} unmatched spreadsheet rows · {metricImportReport.ambiguous_count} ambiguous</span><span>{metricImportReport.unmatched_vfstr_count} VFSTR faculty without matched metrics · {metricImportReport.failed_import_count} import failures · Snapshot date {metricImportReport.snapshot_date}</span><span>Updated: {metricImportReport.updated_status_count} · Not Updated: {metricImportReport.not_updated_status_count}</span></>}</div>}
  <div className="directory-notice"><Database size={17}/><span>Only authors with a verified VFSTR source are listed. Scopus Search creator names are not treated as verified author identities.</span></div>
  <div className="directory-filters"><label className="directory-search"><span>Search authors</span><div><Search size={16}/><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Name, department, school, or interests"/></div></label><label><span>Department</span><select value={department} onChange={event=>setDepartment(event.target.value)}><option value="">All departments</option>{departments.map(value=><option key={value} value={value}>{value}</option>)}</select></label><label><span>Designation</span><select value={designation} onChange={event=>setDesignation(event.target.value)}><option value="">All designations</option>{designations.map(value=><option key={value} value={value}>{value}</option>)}</select></label><label><span>Research area</span><select value={researchArea} onChange={event=>setResearchArea(event.target.value)}><option value="">All research areas</option>{researchAreas.map(value=><option key={value} value={value}>{value}</option>)}</select></label><label><span>Has Google Scholar profile</span><select value={hasScholar} onChange={event=>setHasScholar(event.target.value)}><option value="">All</option><option value="true">Yes</option><option value="false">No</option></select></label><label><span>Has Scopus profile</span><select value={hasScopus} onChange={event=>setHasScopus(event.target.value)}><option value="">All</option><option value="true">Yes</option><option value="false">No</option></select></label><label><span>Metrics status</span><select value={dataStatus} onChange={event=>setDataStatus(event.target.value)}><option value="">All statuses</option><option value="Updated">Updated</option><option value="Not Updated">Not Updated</option></select></label><label><span>School / discipline</span><select value={school} onChange={event=>setSchool(event.target.value)}><option value="">All schools</option>{schools.map(value=><option key={value} value={value}>{value}</option>)}</select></label><label><span>Sort</span><select value={sort} onChange={event=>setSort(event.target.value)}><option value="name_az">Name A–Z</option><option value="name_za">Name Z–A</option><option value="google_scholar_citations">Google Scholar citations</option><option value="scopus_citations">Scopus citations</option><option value="google_scholar_h_index">Google Scholar h-index</option><option value="scopus_h_index">Scopus h-index</option><option value="google_scholar_i10_index">Google Scholar i10-index</option><option value="publications">Publication count</option></select></label></div>
  {error&&<div className="notice error"><AlertCircle size={16}/>{error}</div>}
  {loading?<div className="empty large">Loading verified VFSTR authors...</div>:authors.length===0?<div className="empty large"><UserRound size={34}/><h3>{error?'Directory unavailable':'No verified VFSTR authors yet'}</h3><p>{error?'The directory could not be loaded.':'A verified university roster or authorized author provider has not been connected. No names or metrics are inferred from publication records.'}</p></div>:<>
   <div className="authors-results-meta"><strong>{total}</strong> verified {total===1?'author':'authors'}{authors[0]?.last_updated&&<span>Updated {new Date(authors[0].last_updated).toLocaleString()}</span>}</div>
  <div className="authors-grid">{authors.map(author=><VFSTRAuthorCard key={author.id} author={author} display={display} openProfile={openProfile}/>)}</div>
   <div className="directory-pagination"><button className="secondary" disabled={page<=1} onClick={()=>setPage(page-1)}>Previous</button><span>Page {page} of {pageCount}</span><button className="secondary" disabled={page>=pageCount} onClick={()=>setPage(page+1)}>Next</button></div>
  </>}
 </section>
}
function VFSTRAuthorCard({author,display,openProfile}){
 const metricDate=author.metrics_date?new Date(`${author.metrics_date}-01T00:00:00`).toLocaleDateString(undefined,{month:'long',year:'numeric'}):'N/A';
 const status=(author.data_status||'').trim();
 const isUpdated=status.toLowerCase()==='updated';
 const hasScholar=author.google_scholar_citations!==null&&author.google_scholar_citations!==undefined;
 const hasScopus=author.scopus_citations!==null&&author.scopus_citations!==undefined;
 const metric=value=>value===null||value===undefined||value===''?<dd className="is-empty">N/A</dd>:<dd>{value}</dd>;
 const tags=[
  author.campus&&{key:'campus',label:author.campus},
  hasScholar&&{key:'scholar',label:'Scholar linked'},
  hasScopus&&{key:'scopus',label:'Scopus linked'},
 ].filter(Boolean);
 return <article className="author-card" key={author.id}>
  <div className="author-card-head">
   <div className="author-avatar" aria-hidden="true">{author.name.replace(/^(Dr|Prof|Mr|Mrs|Ms)\.?\s+/i,'').split(' ').map(part=>part[0]).slice(0,2).join('').toUpperCase()}</div>
   <div className="author-card-identity">
    <h3>{author.name}</h3>
    <p className="author-card-role"><span className="role-designation">{display(author.designation)}</span><span className="role-sep">·</span><span>{display(author.department)}</span></p>
    {tags.length>0&&<div className="author-card-tags">{tags.map(tag=><span className={'author-tag'+(tag.key==='campus'?'':' is-verified')} key={tag.key}>{tag.key==='campus'?tag.label:<><CheckCircle2/>{tag.label}</>}</span>)}</div>}
   </div>
   <span className="verified-mark" title="Verified from official VFSTR faculty directory"><CheckCircle2 size={18}/></span>
  </div>
  <div className="author-card-metrics">
   <section className="author-metric-panel scholar" aria-labelledby={`scholar-${author.id}`}><h4 id={`scholar-${author.id}`}><i aria-hidden="true"/>Google Scholar</h4><dl><div><dt>Citations</dt>{metric(author.google_scholar_citations)}</div><div><dt>h-index</dt>{metric(author.google_scholar_h_index)}</div><div><dt>i10-index</dt>{metric(author.google_scholar_i10)}</div></dl><small>VFSTR CSE April 2026 dataset</small></section>
   <section className="author-metric-panel scopus" aria-labelledby={`scopus-${author.id}`}><h4 id={`scopus-${author.id}`}><i aria-hidden="true"/>Scopus</h4><dl><div><dt>Citations</dt>{metric(author.scopus_citations)}</div><div><dt>h-index</dt>{metric(author.scopus_h_index)}</div><div><dt>Author ID</dt>{author.scopus_author_id?<dd className="is-id" title={author.scopus_author_id}>{author.scopus_author_id}</dd>:<dd className="is-empty" aria-label="Scopus author ID not available">N/A</dd>}</div></dl><small>VFSTR CSE April 2026 dataset</small></section>
  </div>
  <div className="author-status-row"><span className={'author-status-pill '+(isUpdated?'is-updated':status?'':'is-muted')}>{isUpdated?'Updated':status||'Status not recorded'}</span><span className="author-status-note">Metrics: {metricDate}</span></div>
  <div className="author-card-body">
   <div className="author-field"><strong>Research interests</strong>{author.research_interests?.length?<div className="author-chips">{author.research_interests.map((interest,index)=><span className="author-chip" key={index}>{interest}</span>)}</div>:<p className="is-empty">N/A</p>}</div>
   <div className="author-field"><strong>Professional memberships</strong>{author.professional_memberships?<p>{author.professional_memberships}</p>:<p className="is-empty">N/A</p>}</div>
  </div>
  <div className="author-card-foot"><span>Official directory · {author.last_updated?new Date(author.last_updated).toLocaleDateString():'N/A'}</span><button className="secondary" onClick={()=>openProfile(author)}>View profile <ChevronRight size={14}/></button></div>
  <div className="author-links">{author.google_scholar_url&&<a href={author.google_scholar_url} target="_blank" rel="noreferrer">Google Scholar <ExternalLink/></a>}{author.scopus_profile_url&&<a href={author.scopus_profile_url} target="_blank" rel="noreferrer">Scopus <ExternalLink/></a>}{author.source_url&&<a href={author.source_url} target="_blank" rel="noreferrer">Official VFSTR source <ExternalLink/></a>}</div>
 </article>
}
function Info({icon,title,text}){return <div className="info"><div className="info-icon">{icon}</div><div><strong>{title}</strong><p>{text}</p></div></div>}
function Metric({label,value,source}){return <div className="metric"><span>{label}</span><strong>{value??'Not synced'}</strong><small>{source}</small></div>}
function ProfilePhoto({profile}){const initials=profile.name.split(' ').map(x=>x[0]).slice(0,2).join('');const [failed,setFailed]=useState(false);return failed||!profile.photo_url?<div className="big-avatar">{initials}</div>:<img className="profile-photo" src={profile.photo_url} alt={`${profile.name} faculty profile`} onError={()=>setFailed(true)}/>}
const CHART_METRICS=[['citations','Citations','citations-bar'],['h_index','h-index','h-index-bar'],['i10_index','i10-index','i10-index-bar']];
const MONTH_ABBR=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
function niceCeil(value){if(!isFinite(value)||value<=0)return 1;const exponent=Math.floor(Math.log10(value));const magnitude=Math.pow(10,exponent);const fraction=value/magnitude;const step=fraction<=1?1:fraction<=2?2:fraction<=2.5?2.5:fraction<=5?5:10;return step*magnitude}
function axisTicks(max,count=4){const out=[];for(let i=0;i<=count;i+=1)out.push(Math.round((max*i)/count));return out.filter((value,index,list)=>list.indexOf(value)===index)}
function shortMonth(label){const parts=String(label||'').split(' ');const index=MONTH_ABBR.indexOf(parts[0]);return index<0?String(label||''):`${MONTH_ABBR[index]} '${(parts[1]||'').slice(2)}`}
function formatDelta(value){if(value===null||value===undefined)return '—';if(value===0)return '0';return value>0?`+${value}`:String(value)}
function FacultyEdit({profile,onSave}){const [interests,setInterests]=useState((profile.research_interests||[]).join(', '));const [photo,setPhoto]=useState(profile.photo_url||'');const [saving,setSaving]=useState(false);const submit=async event=>{event.preventDefault();setSaving(true);await onSave({research_interests:interests.split(',').map(value=>value.trim()).filter(Boolean),photo_url:photo.trim()||null});setSaving(false)};return <details className="profile-edit"><summary>Edit faculty details</summary><form onSubmit={submit}><label>Research interests <textarea value={interests} onChange={event=>setInterests(event.target.value)} placeholder="Machine Learning, Data Mining" rows="3"/></label><label>Profile photo URL <input value={photo} onChange={event=>setPhoto(event.target.value)} placeholder="https://..." type="url"/></label><button className="primary" disabled={saving}>{saving?'Saving...':'Save changes'}</button></form></details>}
function MonthlySourceChart({profile}){
 const [report,setReport]=useState({months:[]});
 const [source,setSource]=useState('google_scholar');
 const [hidden,setHidden]=useState({});
 const [hovered,setHovered]=useState(null);
 useEffect(()=>{let active=true;apiFetch('/api/v1/faculty/'+profile.id+'/monthly-history').then(response=>response.ok?response.json():null).then(result=>{if(active&&result)setReport(result)}).catch(()=>{});return()=>{active=false}},[profile.id]);
 const months=report.months||[];
 const sourceLabel=source==='google_scholar'?'Google Scholar':'Scopus';
 const valuesFor=month=>month?month[source==='google_scholar'?'scholar_metrics':'scopus_metrics']||{}:{};
 const availableMonths=months.filter(month=>month.available);
 const lastAvailable=availableMonths[availableMonths.length-1]||null;
 const prevAvailable=availableMonths[availableMonths.length-2]||null;
 const maxValue=Math.max(0,...availableMonths.flatMap(month=>CHART_METRICS.map(([key])=>valuesFor(month)[key]||0)));
 const scaleMax=niceCeil(maxValue)||1;
 const ticks=axisTicks(scaleMax).slice().reverse();
 const activeMetrics=CHART_METRICS.filter(([key])=>!hidden[key]);
 const barWidth=activeMetrics.length?Math.min(34,Math.floor(88/activeMetrics.length)):0;
 const plotted=months.map(month=>({month,values:valuesFor(month),available:month.available}));
 const hasAnyData=availableMonths.length>0;
 const tooltip=hovered?plotted.find(item=>item.month.month===hovered):null;
 const toggleMetric=key=>setHidden(current=>({...current,[key]:!current[key]}));
 const pendingCount=months.length-availableMonths.length;
 return <section className="monthly-report source-chart">
  <div className="section-head"><div><span className="label">MONTHLY HISTORY</span><h3>{sourceLabel} tracking — {report.start_month||'current month'} to {report.end_month||'12 months'}</h3><p>Toggle source to compare citations, h-index, and i10-index across the 12-month tracking window.</p></div><div className="source-toggle" role="group" aria-label="Metric source"><button className={source==='google_scholar'?'active':''} onClick={()=>setSource('google_scholar')}>Google Scholar</button><button className={source==='scopus'?'active':''} onClick={()=>setSource('scopus')}>Scopus</button></div></div>
  <div className="metric-chart-legend">{CHART_METRICS.map(([key,label,style])=><button type="button" key={key} className={'legend-chip '+style+(hidden[key]?' is-off':'')} aria-pressed={!hidden[key]} onClick={()=>toggleMetric(key)}><i className={style}/>{label}</button>)}</div>
  {!hasAnyData?<div className="chart-empty"><BarChart3 size={30}/><strong>No captured values yet</strong><span>{sourceLabel} metrics appear here after the first sync in the tracking window.</span></div>:<div className="chart-frame">
   <div className="chart-axis">{ticks.map(value=><span key={value}>{value}</span>)}</div>
   <div className="chart-plot" style={{'--chart-cols':plotted.length}}>
    <div className="chart-gridlines" aria-hidden="true">{ticks.map(value=><span key={value}/>)}</div>
    <div className="chart-columns">
     {plotted.map(item=>item.available?<div className="chart-col" key={item.month.month} onMouseEnter={()=>setHovered(item.month.month)} onMouseLeave={()=>setHovered(current=>current===item.month.month?null:current)} tabIndex={0} onFocus={()=>setHovered(item.month.month)} onBlur={()=>setHovered(current=>current===item.month.month?null:current)}>
      <div className="chart-bars" style={{'--bar-w':barWidth+'px'}}>
       {activeMetrics.map(([key,label,style])=>{const value=item.values[key];const present=value!==null&&value!==undefined;return <span className={'chart-bar '+style+(present?'':' is-missing')} key={key} style={{height:present?Math.max(1.5,(value/scaleMax)*100)+'%':'0%'}} title={`${item.month.label} · ${sourceLabel} ${label}: ${present?value:'not captured'}`}><b className="chart-bar-value">{present?value:''}</b></span>})}
      </div>
     </div>:<div className={'chart-col chart-col-pending'+(item.month.month===report.start_month?' is-current':'')} key={item.month.month} onMouseEnter={()=>setHovered(item.month.month)} onMouseLeave={()=>setHovered(current=>current===item.month.month?null:current)} title={`${item.month.label} · awaiting first capture`}><span className="chart-pending-mark"/></div>)}
    </div>
    {tooltip&&<div className="chart-tooltip" role="status"><strong>{tooltip.month.label}</strong>{tooltip.available?activeMetrics.map(([key,label,style])=><span key={key}><i className={style}/>{label}<b>{tooltip.values[key]===null||tooltip.values[key]===undefined?'—':tooltip.values[key]}</b></span>):<span className="chart-tooltip-note"><Clock3/>Awaiting first capture</span>}</div>}
   </div>
  </div>}
  <div className="chart-months" style={{'--chart-cols':Math.max(1,plotted.length)}}>{plotted.map(item=><span key={item.month.month} className={(item.available?'':'is-pending ')+(item.month.month===report.start_month?'is-current':'')}>{shortMonth(item.month.label)}</span>)}</div>
  <div className="chart-summary">
   {CHART_METRICS.map(([key,label,style])=>{const current=lastAvailable?valuesFor(lastAvailable)[key]:null;const previous=prevAvailable?valuesFor(prevAvailable)[key]:null;const delta=current!==null&&current!==undefined&&previous!==null&&previous!==undefined?current-previous:null;return <div className="chart-stat" key={key}><span><i className={style}/>{label}</span><strong>{current===null||current===undefined?'Not captured':current}</strong><small>{prevAvailable?`Change since ${shortMonth(prevAvailable.label)}: ${formatDelta(delta)}`:`Baseline captured ${lastAvailable?shortMonth(lastAvailable.label):'—'}`}</small></div>})}
   <div className="chart-stat chart-stat-note"><span><Clock3/>{pendingCount} month{pendingCount===1?'':'s'} awaiting capture</span><small>Every month from {shortMonth((months[0]||{}).label||report.start_month)} to {shortMonth((months[months.length-1]||{}).label||report.end_month)} is shown; pending months stay empty until their first sync.</small></div>
  </div>
 </section>
}
function Profile({profile,metrics,sync,syncing,lastSync,updateConnections,updateFacultyDetails}){return <div className="profile"><div className="profile-head"><div className="identity"><ProfilePhoto profile={profile}/><div><span className="eyebrow">FACULTY RESEARCH PROFILE</span><h2>{profile.name}</h2><p>{profile.designation||'Faculty'} · {profile.institution}{profile.department?' · '+profile.department:''}</p><div className="ids">{profile.scopus_author_id&&<span>Scopus ID: {profile.scopus_author_id}</span>}{profile.orcid&&<span>ORCID: {profile.orcid}</span>}</div></div></div><div className="profile-actions"><button className="secondary" onClick={sync} disabled={syncing}><RefreshCw size={16}/>{syncing?'Syncing...':'Sync now'}</button>{profile.google_scholar_url&&<a className="secondary link" href={profile.google_scholar_url} target="_blank" rel="noreferrer">Scholar <ExternalLink size={14}/></a>}{profile.scopus_profile_url&&<a className="secondary link" href={profile.scopus_profile_url} target="_blank" rel="noreferrer">Scopus <ExternalLink size={14}/></a>}</div></div>
 {lastSync?.changed?.length>0&&<div className="changes"><CheckCircle2/><div><strong>Changes detected</strong>{lastSync.changed.map((x,i)=><span key={i}>{x}</span>)}</div></div>}
 <div className="source-badges"><span><Database/> Scopus Search {metrics.scopus_search?'Connected':'Not synced'}</span><span><BookOpen/> Google Scholar {metrics.google_scholar?'Live connected':profile.google_scholar_url?'Profile linked · Not synced':'Profile not linked'}</span><span><Clock3/> Last sync: {profile.last_synced_at?new Date(profile.last_synced_at).toLocaleString():'Never'}</span></div>
 <FacultyEdit profile={profile} onSave={updateFacultyDetails}/><MonthlySourceChart profile={profile}/>
 <VFSTRResearchSnapshot profile={profile}/>
 <div className="current-metrics-head"><div><span className="label">CURRENT SOURCE METRICS</span><h3>Live research values</h3></div><span>{metrics.scopus_search||metrics.google_scholar?'Partially synced':'Not synced'}</span></div>
 <div className="metric-grid"><Metric label="Scopus citations*" value={metrics.scopus_search?.citations} source="Computed from retrieved Scopus publications"/><Metric label="Scopus h-index*" value={metrics.scopus_search?.h_index} source="Computed from retrieved Scopus publications"/><Metric label="Scopus i10-index*" value={metrics.scopus_search?.i10_index} source="Computed from retrieved Scopus publications"/><Metric label="Google Scholar citations" value={metrics.google_scholar?.citations} source="Google Scholar"/><Metric label="Google Scholar h-index" value={metrics.google_scholar?.h_index} source="Google Scholar"/><Metric label="Google Scholar i10-index" value={metrics.google_scholar?.i10_index} source="Google Scholar"/></div>
 <div className="metric-note">* Scopus Search API-derived metrics are computed from the publications retrieved by the current search. They are not the restricted official Scopus Author Profile metrics.</div><ConnectionCard profile={profile} updateConnections={updateConnections}/>
 <section className="table-card"><div className="section-head"><div><span className="label">PUBLICATIONS</span><h3>Research output</h3></div><BookOpen size={18}/></div>{profile.publications.length?<div className="pub-table">{profile.publications.map(p=><div className="pub" key={p.id}><div><strong>{p.title}</strong><span>{p.journal||'Publication'} · {p.year||'Year n/a'} · {p.source}</span></div><b>{p.citations??0} cited</b>{p.url&&<a href={p.url} target="_blank"><ExternalLink size={14}/></a>}</div>)}</div>:<div className="empty">No publications have been synchronized yet. Configure a Scopus API key and click Sync now.</div>}</section>
 </div>}
function VFSTRResearchSnapshot({profile}){
 if(!profile.metrics_date&&!profile.vfstr_source_url)return null;
 const show=value=>value===null||value===undefined||value===''?'N/A':value;
 const metricsLabel=profile.metrics_date==='2026-04'?'April 2026':profile.metrics_date||'N/A';
 const currentSync=profile.source_status?.scopus_search||profile.source_status?.google_scholar;
 return <section className="vfstr-profile-data">
  <div className="section-head"><div><span className="label">VERIFIED VFSTR DATA</span><h3>Historical research snapshot — {metricsLabel}</h3></div><span className={'status-pill '+(profile.metrics_data_status==='Updated'?'updated':'')}>{show(profile.metrics_data_status)}</span></div>
  <div className="profile-source-grid">
  <section><h4>Google Scholar</h4><SnapshotMetric label="Citations" value={profile.google_scholar_citations} source="Google Scholar — VFSTR CSE April 2026 dataset"/><SnapshotMetric label="h-index" value={profile.google_scholar_h_index} source="Google Scholar — VFSTR CSE April 2026 dataset"/><SnapshotMetric label="i10-index" value={profile.google_scholar_i10} source="Google Scholar — VFSTR CSE April 2026 dataset"/>{profile.google_scholar_url&&<a className="source-link" href={profile.google_scholar_url} target="_blank" rel="noreferrer">Google Scholar profile <ExternalLink size={13}/></a>}</section>
  <section><h4>Scopus</h4><SnapshotMetric label="Citations" value={profile.scopus_citations} source="Scopus — VFSTR CSE April 2026 dataset"/><SnapshotMetric label="h-index" value={profile.scopus_h_index} source="Scopus — VFSTR CSE April 2026 dataset"/><SnapshotMetric label="Author ID" value={profile.scopus_author_id} source="Supplied by VFSTR CSE April 2026 dataset"/>{profile.scopus_profile_url&&<a className="source-link" href={profile.scopus_profile_url} target="_blank" rel="noreferrer">Scopus profile <ExternalLink size={13}/></a>}</section>
  </div>
  <div className="official-faculty-data"><div><strong>Designation</strong><span>{show(profile.designation)}</span></div><div><strong>Department</strong><span>{show(profile.department)}</span></div><div><strong>Research interests</strong><span>{profile.research_interests?.length?profile.research_interests.join(' · '):'N/A'}</span></div><div><strong>Professional memberships</strong><span>{show(profile.professional_memberships)}</span></div>{profile.vfstr_source_url&&<a className="source-link" href={profile.vfstr_source_url} target="_blank" rel="noreferrer">Verified from official VFSTR faculty directory <ExternalLink size={13}/></a>}</div>
  <p className="metric-note">These values come from the April 2026 spreadsheet snapshot, not a live sync. Current source status: {currentSync||'Not synced'}.</p>
 </section>
}
function SnapshotMetric({label,value,source}){return <div className="metric"><span>{label}</span><strong>{value===null||value===undefined||value===''?'N/A':value}</strong><small>{source}</small></div>}
function ConnectionCard({profile,updateConnections}){const [url,setUrl]=useState(profile.google_scholar_url||'');const [dept,setDept]=useState(profile.department||'');const [orc,setOrc]=useState(profile.orcid||'');const save=e=>{e.preventDefault();updateConnections({google_scholar_url:url||null,department:dept,orcid:orc||null})};return <section className="table-card connection"><div className="section-head"><div><span className="label">PROFILE CONNECTIONS</span><h3>Source identifiers</h3></div><Link2 size={18}/></div><form className="connection-form" onSubmit={save}><div><label>Google Scholar public profile URL</label><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://scholar.google.com/citations?user=..."/><small>Used by the optional Scholar provider adapter.</small></div><div><label>ORCID</label><input value={orc} onChange={e=>setOrc(e.target.value)} placeholder="0000-0000-0000-0000"/></div><div><label>Department</label><input value={dept} onChange={e=>setDept(e.target.value)} placeholder="Computer Science and Engineering"/></div><button className="primary">Save connections</button></form></section>}
function HistoryPage({items,open,remove,clear}){return <section className="history"><div className="section-head"><div><span className="label">SEARCH HISTORY</span><h2>Previously searched faculty</h2><p>Profiles are retained so you can reopen them without repeating the lookup.</p></div>{items.length>0&&<button className="danger" onClick={clear}><Trash2 size={15}/>Clear all</button>}</div>{!items.length?<div className="empty large"><History size={38}/><h3>No searches yet</h3><p>Faculty profiles you open will appear here.</p></div>:<div className="history-list">{items.map(x=><div className="history-item" key={x.id}><div className="history-avatar">{x.faculty_name.split(' ').map(y=>y[0]).slice(0,2).join('')}</div><div><strong>{x.faculty_name}</strong><span><Building2 size={13}/>{x.institution}</span><small><Clock3 size={12}/>{new Date(x.searched_at).toLocaleString()}</small></div><div className="history-actions"><button onClick={()=>open(x.faculty_id)}>View profile <ChevronRight size={15}/></button><button className="icon-danger" title="Delete" onClick={()=>remove(x.id)}><Trash2 size={15}/></button></div></div>)}</div>}</section>}
createRoot(document.getElementById('root')).render(<App/>);
export {App};
